INSERT INTO APP.ACCOUNT(ID, DTYPE, EMAIL, PASSWORD) VALUES(1, 'Administrator', 'admin@sharkz.de', '123456');
INSERT INTO APP.ACCOUNT(ID, DTYPE, EMAIL, PASSWORD) VALUES(1, 'Customer', 'michi@gmail.de', '123456');
INSERT INTO APP.ACCOUNT(ID, DTYPE, EMAIL, PASSWORD) VALUES(1, 'Customer', 'jonas@sharkz.de', '123456');
INSERT INTO APP.ACCOUNT(ID, DTYPE, EMAIL, PASSWORD) VALUES(1, 'Customer', 'simon@sharkz.de', '123456');
